parameters:
    route.request_context.scheme: '%env(APP_SCHEME)%'
    route.request_context.host: '%env(APP_HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
